<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoice - Order #{{ $order->id }}</title>
    <style>
        body { font-family: DejaVu Sans, Arial, Helvetica, sans-serif; color:#111; }
        .header { text-align:center; margin-bottom:20px }
        .logo { height:48px }
        .meta { margin-bottom:20px }
        .items { width:100%; border-collapse:collapse }
        .items th, .items td { border:1px solid #ddd; padding:8px }
        .items th { background:#f5f5f5; }
        .right { text-align:right }
        .total { font-weight:700 }
    </style>
</head>
<body>
    <div class="header">
        <img class="logo" src="https://res.cloudinary.com/dgrnbtgts/image/upload/v1771338287/gizmo_qsab1d.png" alt="Gizmo Store">
        <h2>Invoice</h2>
        <div>Order #{{ $order->id }}</div>
        <div>{{ $order->created_at->format('M d, Y H:i') }}</div>
    </div>

    <div class="meta">
        <strong>Customer:</strong> {{ $order->user->name }} ({{ $order->user->email }})<br>
        <strong>Shipping Address:</strong> {{ $order->shipping_address ?? 'N/A' }}
    </div>

    <table class="items">
        <thead>
            <tr>
                <th>Item</th>
                <th class="right">Qty</th>
                <th class="right">Price</th>
                <th class="right">Subtotal</th>
            </tr>
        </thead>
        <tbody>
            @foreach($order->items as $item)
                <tr>
                    <td>{{ $item->product->name ?? $item->name ?? 'Item' }}</td>
                    <td class="right">{{ $item->quantity }}</td>
                    <td class="right">@currency($item->price)</td>
                    <td class="right">@currency($item->price * $item->quantity)</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="right">Subtotal</td>
                <td class="right">@currency($order->subtotal ?? $order->total)</td>
            </tr>
            <tr>
                <td colspan="3" class="right">Shipping</td>
                <td class="right">@currency($order->shipping_cost ?? 0)</td>
            </tr>
            <tr>
                <td colspan="3" class="right total">Total</td>
                <td class="right total">@currency($order->total)</td>
            </tr>
        </tfoot>
    </table>

    <p style="margin-top:24px; font-size:12px; color:#666">This is an automated invoice generated by GIZMO Store.</p>
</body>
</html>
